# Generated by Django 3.2.25 on 2024-05-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emeail',
            new_name='email',
        ),
    ]
